theme: jekyll-theme-cayman
title: Codebasis zur Bachelorarbeit:
description: Erstellung eines prototypischen Systems zur Extraktion und semantischen Einordnung von Texten aus Rastergrafiken im RGB Farbraum auf Basis neuronaler Netze am Beispiel einer Liste von Lebensmittelinhaltsstoffen
show_downloads: true
